---
title: "Estimation of Angle of Significance in Human Joint Angles Using Extended Kalman Filter and Principal Component Analysis (Unpublished)"
collection: Conference Papers
permalink: /publication/2025-01-20-apscon-kalman-pca
excerpt: 'Human Motion Analysis (HMA) is a pivotal multidisciplinary field that leverages advanced signal processing and machine learning techniques to interpret human movement patterns. This paper explores a newly developed wireless wearable device that consists of Inertial Measurement Unit (IMU) sensors along with its usage in the estimation of human joint angles using a combination of Extended Kalman Filter (EKF) and Principal Component Analysis (PCA). The integration of EKF, a dynamic algorithm adept at estimating joint angles while accounting for noise, and PCA, a technique for dimensionality reduction and principal component identification, enhances the precision of motion analysis. Additionally, the results obtained in this study are validated using YOLOv7, ensuring the reliability and accuracy of the joint angle estimations. Hence, the study explains the collective effort of the design of the IMU-based wearable device, data collection, analysis, and validation of the joint angle estimations highlighting the accuracy and applicability of results in various domains, including medical diagnostics, sports performance, and industrial applications.'
date: 2025-01-20
venue: '2025 IEEE Applied Sensing Conference (APSCON) (unpublished)'
# paperurl: 'http://academicpages.github.io/files/mercon2024.pdf'
# citation: 'M. Pandukabhaya et al., "Quality Assessment of Welding using Regression Analysis of Biomechanical Data," <i>2025 Moratuwa Engineering Research Conference (MERCon)</i>, Hyderabad, India, 2025, pp. 376-381, doi: 10.1109/APSCON63886.2024.10689188.'
# doi: "10.1109/APSCON63886.2024.10689188"
---

Human Motion Analysis (HMA) is a pivotal multidisciplinary field that leverages advanced signal processing and machine learning techniques to interpret human movement patterns. This paper explores a newly developed wireless wearable device that consists of Inertial Measurement Unit (IMU) sensors along with its usage in the estimation of human joint angles using a combination of Extended Kalman Filter (EKF) and Principal Component Analysis (PCA). The integration of EKF, a dynamic algorithm adept at estimating joint angles while accounting for noise, and PCA, a technique for dimensionality reduction and principal component identification, enhances the precision of motion analysis. Additionally, the results obtained in this study are validated using YOLOv7, ensuring the reliability and accuracy of the joint angle estimations. Hence, the study explains the collective effort of the design of the IMU-based wearable device, data collection, analysis, and validation of the joint angle estimations highlighting the accuracy and applicability of results in various domains, including medical diagnostics, sports performance, and industrial applications.
